version: '3.8'

services:
  redis:
    image: redis:7
    ports:
      - '6379:6379'

  backend:
    build: ./apps/backend
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=supersecret
    ports:
      - '3000:3000'
    depends_on:
      - redis

  frontend:
    build: ./apps/frontend
    ports:
      - '5173:5173'
